### ISSUE TITLE
fig: predicted vs observed by model type

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-R/protoloads#57]
![img_20180510_162024642](https://user-images.githubusercontent.com/12039957/40321995-c39c2274-5ce5-11e8-8c9d-3d5f3b93f59b.jpg)

probably pick 1 or two lead times and just stick with those? or color by lead time? main focus should be model type

**Comment by jzwart** [comment]
I can start working on this

**Comment by jzwart** [comment]
This is with just a lead time of 0 or 1 days and y and x-axes are the same. dotted line is 1:1 line. I can change the color scheme but added a .yml so that this can be easily changed from fig_config.yml: 
![image](https://user-images.githubusercontent.com/4825431/41128901-63306fd8-6a75-11e8-879a-c0575e49c9ff.png)

**Comment by aappling-usgs** [comment]
Whooooeeey, site number 3! That's some crazy autocorrelated error!

It's too bad all the points are compressed for site 2, but otherwise I think this plot shows exactly the info I'd want. Opens up discussions about bias and autocorrelation but also makes it clear that the predictions can be pretty decent when conditions are right :+1:
